Viajah/Models/Regiao.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Viajah.Models
{
    public partial class Regiao
    {
        public Regiao()
        {
            UsuarioDetalhe = new HashSet<UsuarioDetalhe>();
        }

        public int Id { get; set; }

        [Required]
        [StringLength(255)]
        public string Descricao { get; set; }

        [Required]
        [StringLength(100)]
        public string Cidade { get; set; }

        [Required]
        [StringLength(100)]
        public string Pais { get; set; }

        public bool? Aprovada { get; set; }

        public RegiaoComentario RegiaoComentario { get; set; }
        public RegiaoFoto RegiaoFoto { get; set; }
        public ICollection<RegiaoHistoria> RegiaoHistoria { get; set; }
        public RegiaoPontoTuristico RegiaoPontoTuristico { get; set; }
        public ICollection<UsuarioDetalhe> UsuarioDetalhe { get; set; }
    }
}

Viajah/Controllers/RegiaoHistoriasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Viajah.Models;
using Viajah.Services;

namespace Viajah.Controllers
{
    public class RegiaoHistoriasController : Controller
    {
        private readonly ViajahContext _context;

        public RegiaoHistoriasController(ViajahContext context)
        {
            _context = context;
        }

        // GET: RegiaoHistorias
        public async Task<IActionResult> Index()
        {
            var viajahContext = _context.RegiaoHistoria.Include(r => r.IdRegiaoNavigation);
            return View(await viajahContext.ToListAsync());
        }

        // GET: RegiaoHistorias/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var regiaoHistoria = await _context.RegiaoHistoria
                .Include(r => r.IdRegiaoNavigation)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (regiaoHistoria == null)
            {
                return NotFound();
            }

            return View(regiaoHistoria);
        }

        // GET: RegiaoHistorias/Create
        public IActionResult Create(int? id)
        {
            ViewData["Id"] = new SelectList(_context.Regiao, "Id", "Cidade");

            RegiaoHistoria regiaoHistoria = new RegiaoHistoria();
            if (id.HasValue) regiaoHistoria.IdRegiao = id;

            return View(regiaoHistoria);
        }

        // POST: RegiaoHistorias/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Descricao,ExperienciasBoas,ExperienciasRuin,Conclusao,Indicacao,DataPostagem,IdRegiao")] RegiaoHistoria regiaoHistoria)
        {
            if (ModelState.IsValid)
            {
                regiaoHistoria.DataPostagem = DateTime.UtcNow;
                Usuario logged = HttpContext.Session.GetObject<Usuario>("Usuario");
                regiaoHistoria.IdUsuario = logged.Id;
                _context.Add(regiaoHistoria);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["Id"] = new SelectList(_context.Regiao, "Id", "Cidade", regiaoHistoria.Id);
            return RedirectToAction("Details","Regiao",regiaoHistoria.IdRegiao);
        }

        // GET: RegiaoHistorias/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var regiaoHistoria = await _context.RegiaoHistoria.FindAsync(id);
            if (regiaoHistoria == null)
            {
                return NotFound();
            }
            ViewData["Id"] = new SelectList(_context.Regiao, "Id", "Cidade", regiaoHistoria.Id);
            return View(regiaoHistoria);
        }

        // POST: RegiaoHistorias/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Descricao,ExperienciasBoas,ExperienciasRuin,Conclusao,Indicacao,DataPostagem,IdRegiao")] RegiaoHistoria regiaoHistoria)
        {
            if (id != regiaoHistoria.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(regiaoHistoria);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RegiaoHistoriaExists(regiaoHistoria.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["Id"] = new SelectList(_context.Regiao, "Id", "Cidade", regiaoHistoria.Id);
            return View(regiaoHistoria);
        }

        // GET: RegiaoHistorias/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var regiaoHistoria = await _context.RegiaoHistoria
                .Include(r => r.IdRegiaoNavigation)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (regiaoHistoria == null)
            {
                return NotFound();
            }

            return View(regiaoHistoria);
        }

        // POST: RegiaoHistorias/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var regiaoHistoria = await _context.RegiaoHistoria.FindAsync(id);
            _context.RegiaoHistoria.Remove(regiaoHistoria);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RegiaoHistoriaExists(int id)
        {
            return _context.RegiaoHistoria.Any(e => e.Id == id);
        }
    }
}

Viajah/Controllers/RegiaosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Viajah.Models;
using Viajah.Services;

namespace Viajah.Controllers
{
    public class RegiaosController : Controller
    {
        private readonly ViajahContext _context;

        public RegiaosController(ViajahContext context)
        {
            _context = context;
        }

        // GET: Regiaos
        public async Task<IActionResult> Index()
        {
            return View(await _context.Regiao.ToListAsync());
        }

        // GET: Regiaos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var regiao = await _context.Regiao
                .Include(a => a.RegiaoHistoria)
                    .ThenInclude(a => a.IdUsuarioNavigation)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (regiao == null)
            {
                return NotFound();
            }

            return View(regiao);
        }

        // GET: Regiaos/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Regiaos/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Descricao,Cidade,Pais")] Regiao regiao)
        {
            if (ModelState.IsValid)
            {
                bool eModerador = Convert.ToBoolean(HttpContext.Session.GetString("Usuario.Moderador"));
                regiao.Aprovada = (eModerador)?true:false;
                _context.Add(regiao);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index","Home");
            }
            return View(regiao);
        }

        // GET: Regiaos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var regiao = await _context.Regiao.FindAsync(id);
            if (regiao == null)
            {
                return NotFound();
            }
            return View(regiao);
        }

        // POST: Regiaos/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Regiao regiao)
        {
            if (id != regiao.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(regiao);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RegiaoExists(regiao.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(regiao);
        }

        // GET: Regiaos/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var regiao = await _context.Regiao
                .FirstOrDefaultAsync(m => m.Id == id);
            if (regiao == null)
            {
                return NotFound();
            }

            return View(regiao);
        }

        // POST: Regiaos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var regiao = await _context.Regiao.FindAsync(id);
            _context.Regiao.Remove(regiao);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RegiaoExists(int id)
        {
            return _context.Regiao.Any(e => e.Id == id);
        }
    }
}

Viajah/Views/Regiaos/Create.cshtml
@model Viajah.Models.Regiao

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>Regiao</h4>
<hr />
<div class="row">
    <div class="col-md-10">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="Pais" class="control-label"></label>
                <input asp-for="Pais" class="form-control" />
                <span asp-validation-for="Pais" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Cidade" class="control-label"></label>
                <input asp-for="Cidade" class="form-control" />
                <span asp-validation-for="Cidade" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Descricao" class="control-label"></label>
                <textarea asp-for="Descricao" rows="3" class="form-control"></textarea>
                <span asp-validation-for="Descricao" class="text-danger"></span>
            </div>
            
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>

        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Viajah/Views/Regiaos/Delete.cshtml
@model Viajah.Models.Regiao

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Regiao</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Descricao)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Descricao)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Cidade)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Cidade)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Pais)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Pais)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Viajah/Views/Regiaos/Details.cshtml
@using Microsoft.AspNetCore.Http;
@using Viajah.Services;

@inject IHttpContextAccessor HttpContextAccessor

@model Viajah.Models.Regiao

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>
<div class="row">
    <div class="col-md-8">
        <h4>Regiao</h4>
        <hr />

        <div class="card mb-5">
            <img class="card-img-top" src="http://placehold.it/750x300" alt="Card image cap">
            <div class="card-body">
                <h4>@Html.DisplayNameFor(model => model.Cidade)</h4>
                <p class="card-title">@Html.DisplayFor(model => model.Cidade)</p>
                <h4>@Html.DisplayNameFor(model => model.Descricao)</h4>
                <p class="card-text">@Html.DisplayFor(model => model.Descricao)</p>
                <h4>@Html.DisplayNameFor(model => model.Pais)</h4>
                <p class="card-text">@Html.DisplayFor(model => model.Pais)</p>
                <a class="btn btn-secondary" asp-controller="Regiaos" asp-action="Details" asp-route-id="@Model.Id">Mais aqui &rarr;</a>
            </div>
            <div class="card-footer text-muted">
            </div>
        </div>

        <h2>Histórias</h2>
        @if (null != HttpContextAccessor.HttpContext.Session.GetString("Usuario"))
        {
            <p>
                <a asp-controller="RegiaoHistorias" asp-action="Create" asp-route-id="@Model.Id">Criar nova</a>
            </p>
        }

        @await Html.PartialAsync("_PartialListarRegiaoHistoria", Model.RegiaoHistoria)



    </div>
    <div class="col-md-4">
        <!-- Side Widget -->
        <div class="card my-4">
            <h5 class="card-header">Anuncios</h5>
            <div class="card-body">
                Anuncie aqui!
            </div>
        </div>
    </div>
</div>

Viajah/Views/Regiaos/Edit.cshtml
@model Viajah.Models.Regiao

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>Regiao</h4>
<hr />
<div class="row">
    <div class="col-md-10">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />

            <div class="form-group">
                <label asp-for="Pais" class="control-label"></label>
                <input asp-for="Pais" class="form-control" />
                <span asp-validation-for="Pais" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Cidade" class="control-label"></label>
                <input asp-for="Cidade" class="form-control" />
                <span asp-validation-for="Cidade" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Descricao" class="control-label"></label>
                <textarea asp-for="Descricao" class="form-control"  rows="3"></textarea>
                <span asp-validation-for="Descricao" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Aprovada" class="control-label"></label>
                <select asp-for="Aprovada" class="form-control" >
                    <option value="true">Aprovado</option>
                    <option value="false">Reprovado</option>

                </select>
                <span asp-validation-for="Aprovada" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Viajah/Views/Regiaos/Index.cshtml
@model IEnumerable<Viajah.Models.Regiao>

@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<div class="row">
    <div class="col-md-10">
        <table class="table">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Descricao)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Cidade)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Pais)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Aprovada)
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Descricao)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Cidade)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Pais)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Aprovada)
                        </td>
                        <td>
                            <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                            <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>