Viajah/Controllers/RegiaosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Viajah.Models;
using Viajah.Services;

namespace Viajah.Controllers
{
    public class RegiaosController : Controller
    {
        private readonly ViajahContext _context;

        public RegiaosController(ViajahContext context)
        {
            _context = context;
        }

        // GET: Regiaos
        public async Task<IActionResult> Index()
        {
            return View(await _context.Regiao.ToListAsync());
        }

        // GET: Regiaos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var regiao = await _context.Regiao
                .Include(a => a.RegiaoHistoria)
                    .ThenInclude(a => a.IdUsuarioNavigation)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (regiao == null)
            {
                return NotFound();
            }

            return View(regiao);
        }

        // GET: Regiaos/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Regiaos/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Descricao,Cidade,Pais")] Regiao regiao)
        {
            if (ModelState.IsValid)
            {
                bool eModerador = Convert.ToBoolean(HttpContext.Session.GetString("Usuario.Moderador"));
                regiao.Aprovada = (eModerador)?true:false;
                _context.Add(regiao);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index","Home");
            }
            return View(regiao);
        }

        // GET: Regiaos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var regiao = await _context.Regiao.FindAsync(id);
            if (regiao == null)
            {
                return NotFound();
            }
            return View(regiao);
        }

        // POST: Regiaos/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Regiao regiao)
        {
            if (id != regiao.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(regiao);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RegiaoExists(regiao.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(regiao);
        }

        // GET: Regiaos/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var regiao = await _context.Regiao
                .FirstOrDefaultAsync(m => m.Id == id);
            if (regiao == null)
            {
                return NotFound();
            }

            return View(regiao);
        }

        // POST: Regiaos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var regiao = await _context.Regiao.FindAsync(id);
            _context.Regiao.Remove(regiao);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RegiaoExists(int id)
        {
            return _context.Regiao.Any(e => e.Id == id);
        }
    }
}

Viajah/Controllers/UsuariosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Viajah.Models;
using Viajah.Services;

namespace Viajah.Controllers
{
    public class UsuariosController : Controller
    {
        private readonly ViajahContext _context;

        public UsuariosController(ViajahContext context)
        {
            _context = context;
        }

        // GET: Usuarios
        public async Task<IActionResult> Index()
        {
            return View(await _context.Usuario.ToListAsync());
        }

        // GET: Usuarios/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var usuario = await _context.Usuario
                .FirstOrDefaultAsync(m => m.Id == id);
            if (usuario == null)
            {
                return NotFound();
            }

            return View(usuario);
        }

        // GET: Usuarios/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Usuarios/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Login,Senha,Nome,Email,DataCadastro,Moderador")] Usuario usuario)
        {
            if (ModelState.IsValid)
            {
                usuario.DataCadastro = DateTime.UtcNow;
                usuario.Moderador = false;
                _context.Add(usuario);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Login));
            }
            return RedirectToAction("Index","Home");
        }

        // GET: Usuarios/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var usuario = await _context.Usuario.FindAsync(id);
            if (usuario == null)
            {
                return NotFound();
            }
            return View(usuario);
        }

        // POST: Usuarios/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Login,Senha,Nome,Email,DataCadastro,Moderador")] Usuario usuario)
        {
            if (id != usuario.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(usuario);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UsuarioExists(usuario.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(usuario);
        }

        // GET: Usuarios/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var usuario = await _context.Usuario
                .FirstOrDefaultAsync(m => m.Id == id);
            if (usuario == null)
            {
                return NotFound();
            }

            return View(usuario);
        }

        // POST: Usuarios/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var usuario = await _context.Usuario.FindAsync(id);
            _context.Usuario.Remove(usuario);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UsuarioExists(int id)
        {
            return _context.Usuario.Any(e => e.Id == id);
        }

        public  IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Login(Usuario usuario)
        {
            Usuario login = _context.Usuario.Where(u => u.Login == usuario.Login && u.Senha == usuario.Senha).FirstOrDefault();

            if(login != null)
            {
                HttpContext.Session.SetObject("Usuario", login);

                if (login.Moderador.Value)
                {
                    HttpContext.Session.SetString("Usuario.Moderador", login.Moderador.ToString());
                }
            }

            return RedirectToAction("Index", "Home");
        }
    }
}

Viajah/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http;
@using Viajah.Services;

@inject IHttpContextAccessor HttpContextAccessor

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Viajah</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/css/bootstrap.min.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link href="~/css/blog-home.css" rel="stylesheet">
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="~/css/bootstrap.min.css" />
        <link href="~/css/blog-home.css" rel="stylesheet" asp-append-version="true">
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
        <div class="container">
            <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Viajah</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    @if (null != HttpContextAccessor.HttpContext.Session.GetString("Usuario.Moderador"))
                    {
                        <li><a asp-area="" asp-controller="Usuarios" asp-action="Index" class="nav-link">Usuarios</a></li>
                    }
                    @if (null != HttpContextAccessor.HttpContext.Session.GetString("Usuario.Moderador"))
                    {
                        <li><a asp-area="" asp-controller="Regiaos" asp-action="Index" class="nav-link">Regioes</a></li>
                    }
                    @if (null == HttpContextAccessor.HttpContext.Session.GetString("Usuario"))
                    {
                        <li><a asp-area="" asp-controller="Usuarios" asp-action="Login" class="nav-link">Login</a></li>
                    }
                    @if (null != HttpContextAccessor.HttpContext.Session.GetString("Usuario"))
                    {
                        var nomeUsuairo = HttpContextAccessor.HttpContext.Session.GetObject<Usuario>("Usuario").Nome;
                        <li class="nav-link">Usuario: @nomeUsuairo</li>
                    }
                    @if (null != HttpContextAccessor.HttpContext.Session.GetString("Usuario"))
                    {
                        <li class="nav-link"><a asp-controller="Home" asp-action="Logout">Log out</a></li>
                    }
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        <div class="col-md-12">

            @RenderBody()

        </div>
        <hr />
        <footer>
            <p>&copy; 2018 - Viajah</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/js/jquery.min.js"></script>
        <script src="~/js/bootstrap.bundle.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="~/js/jquery.min.js"></script>
        <script src="~/js/bootstrap.bundle.min.js"></script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

Viajah/Views/Shared/_PartialListarRegiaoHistoria.cshtml
@model IEnumerable<Viajah.Models.RegiaoHistoria>

@foreach (var item in Model)
{
    <div class="card mb-4">
        <div class="card-body">
            <h5>Usuario: @Html.DisplayFor(model => item.IdUsuarioNavigation.Nome)</h5>

            <h5> @Html.DisplayNameFor(model => model.Descricao)</h5>
            <p class="card-title">@Html.DisplayFor(model => item.Descricao)</p>

            <h5> @Html.DisplayNameFor(model => model.ExperienciasBoas)</h5>
            <p class="card-title">@Html.DisplayFor(model => item.ExperienciasBoas)</p>

            <h5> @Html.DisplayNameFor(model => model.ExperienciasRuin)</h5>
            <p class="card-title">@Html.DisplayFor(model => item.ExperienciasRuin)</p>

            <h5> @Html.DisplayNameFor(model => model.Conclusao)</h5>
            <p class="card-title">@Html.DisplayFor(model => item.Conclusao)</p>

            <h5> @Html.DisplayNameFor(model => model.Indicacao)</h5>
            <p class="card-title">@Html.DisplayFor(model => item.Indicacao)</p>

            <h5> @Html.DisplayNameFor(model => model.Descricao)</h5>
            <p class="card-title">@Html.DisplayFor(model => item.Descricao)</p>
        </div>
        <div class="card-footer text-muted">
            @Html.DisplayNameFor(model => model.DataPostagem): @Html.DisplayFor(model => item.DataPostagem)
        </div>
    </div>
}